title: Flymon plugin for Wodpress
description: A WordPress plugin to display the lowest flight price for a given route/dates in your blog.
google_analytics: 
show_downloads: false
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
